name: council-test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: record
        run: |
          curl -s "https://record.council.jeju.kr/CLRecords/Retrieval2/index.php?hfile=13A0110453011.html&daesu=13" | wc -c
